// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grdimoqcrfggdvaabhqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyZGltb3FjcmZnZ2R2YWFiaHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDI2MDUsImV4cCI6MjA2NDY3ODYwNX0.ilevCaKIcNftk4VTVl0h0g45J8rwQu5Iw5RaeHom8-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);